spring.application.name=event-ticketing-service

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:ticketingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL Logging
spring.jpa.show-sql=true

# --- Swagger / OpenAPI Configuration ---
# Change the path to the UI (Optional - default is /swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Change the path to the JSON API Definition (Optional - default is /v3/api-docs)
springdoc.api-docs.path=/api-docs

# Enable the try-it-out button by default
springdoc.swagger-ui.try-it-out-enabled=true

# If you want to run the app on a different port than 8080
# server.port=8081